### PR TITLE
fix(summary): remove summary page, move logic to correct place

### LINKED ISSUE #147: (summary) remove summary page

### PR DESCRIPTION
**Pull request by RobbertWolfs**
fixes #147

### CODE REVIEW

File: src/pages/knockout.vue [hunk 1]
```diff
@@ -35,6 +35,15 @@ export default {
 
   beforeMount() {
     this.splitRounds();
```
Comment (WartClaes) [inline src/pages/knockout.vue]: remove

File: src/pages/teams.vue [hunk 2]
```diff
@@ -53,8 +54,16 @@ export default {
     },
 
     submit() {
-      if (this.randomly) this.$router.push(`/random/${this.slug}`);
-      else this.$router.push(`/summary/${this.slug}`);
+      if (this.randomly) {
+        this.$router.push(`/random/${this.slug}`);
+      }
+      else {
```
Comment (WartClaes) [inline src/pages/teams.vue]: `} else {`
